language: python
dist: trusty

python:
  - "2.7"

sudo: required

cache:
  pip: true
  directories:
    - $HOME/buildout-cache

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - libappindicator1
      - fonts-liberation
      - chromium-browser
      - chromium-chromedriver

env:
  - VERSION="9.0" ODOO_TEST="1" ROBOT="1" DOC="1"

virtualenv:
  system_site_packages: true

before_install:
  - wget http://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo chmod u+x chromedriver
  - sudo mv chromedriver /usr/bin/
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - ./travis_before_install

install:
  - ./travis_install

script:
  - bin/test_openerp -d openerp_test -i account,sale,stock,web_selenium
  - bin/supervisord
  - sleep 5
  - bin/pybot -v CONFIG:config_80.py robot/sale_stock_invoice_workflow.robot
  - bin/travis-sphinx build

after_success:
  - bin/travis-sphinx deploy


